apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sharkapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/atwin140/demo-gitops.git
    targetRevision: main
    path: sharkapp/overlays/prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: sharkapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
