apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sharkapp-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/atwin140/demo-gitops.git
    targetRevision: dev
    path: sharkapp/overlays/dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: sharkapp-dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
